# -*- coding: utf-8 -*-
"""NamesAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sDCO4dS577ZbJx2rt3PDc6sM1KQMHAkD
"""

# Importing Libraries
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

# Read CSV
students = pd.read_csv('names.csv')

# Read Data
students.head()

# Lowercase the Names in Names column
students['Name'] = students['Name'].str.lower()

# Read Data
students.head()

# Length of students
len(students)

# Format the output
print(f"There are {len(students)} students on the roster")

# Count the values of each type in column 
students['Sex'].value_counts().to_frame()

# Plotting of length of names
sns.distplot(students['Name'].str.len(), rug=True, bins=np.arange(12), axlabel="Number of characters")
plt.xlim(0, 12)
plt.xticks(np.arange(12))
plt.ylabel("Proportion per character")

students['Name'][15]

#Uses Pivot Table function to calculate frequency of sex per year
pivot_year_name_count = pd.pivot_table(students, index='Year', columns='Sex', values='Count', aggfunc=np.sum)

#Color to differentiate
pink_blue = ['#E188DB', '#334FFF']

# Plotting
with sns.color_palette(sns.color_palette(pink_blue)):
  pivot_year_name_count.plot(marker=".")
  plt.title("Registered Names vs Year stratified by sex")
  plt.ylabel("Names Registered that Year")

